/* ==========================================================================
   LYVORA — Product Catalog (demo data)
   Images reuse the brand's category art (no per-product photography supplied),
   tinted per item via CSS filters so each still reads as distinct.
   ========================================================================== */

const ASSET = (name) => `${window.LYVORA_ROOT || ''}assets/images/${name}`;

const PRODUCTS = [
  // ---- Makeup ----
  { id:'mk-01', category:'makeup', name:'Velvet Rose Matte Lipstick', price:420, oldPrice:520, rating:4.8, reviews:214, badge:'Best Seller', img:'background_makeup.webp', desc:'A weightless matte lipstick in a timeless rose, built to last through dinner and diplomacy alike.', ingredients:'Castor Seed Oil, Candelilla Wax, Vitamin E, Mica, Iron Oxides.', usage:'Glide from the center of the lips outward. One coat for a wash of color, two for full pigment.' },
  { id:'mk-02', category:'makeup', name:'Silk Veil Foundation', price:650, rating:4.6, reviews:132, badge:'New', img:'background_makeup.webp', desc:'A buildable, second-skin foundation that blurs pores without masking the skin underneath.', ingredients:'Squalane, Hyaluronic Acid, Silica, Titanium Dioxide.', usage:'Warm a pea-sized amount between fingers, press into skin starting from the center of the face.' },
  { id:'mk-03', category:'makeup', name:'Golden Hour Eyeshadow Palette', price:780, oldPrice:920, rating:4.9, reviews:301, badge:'Best Seller', img:'background_makeup.webp', desc:'Nine warm-toned shades that move from soft matte to molten metallic for day-to-night eyes.', ingredients:'Mica, Talc, Dimethicone, Synthetic Fluorphlogopite.', usage:'Pat metallics with a fingertip, blend mattes with a soft brush for a seamless transition.' },
  { id:'mk-04', category:'makeup', name:'Aura Glow Highlighter', price:390, rating:4.7, reviews:98, img:'background_makeup.webp', desc:'A fine-milled highlighter that sits on the skin like candlelight rather than glitter.', ingredients:'Mica, Boron Nitride, Jojoba Esters.', usage:'Sweep along cheekbones, brow bone, and cupid\u2019s bow for a lit-from-within finish.' },
  { id:'mk-05', category:'makeup', name:'Precision Ink Eyeliner', price:310, rating:4.5, reviews:76, img:'background_makeup.webp', desc:'An ultra-fine felt tip for a crisp line that holds for sixteen hours without flaking.', ingredients:'Water, Acrylates Copolymer, Iron Oxides.', usage:'Rest the tip at the lash line and draw in one continuous motion.' },
  { id:'mk-06', category:'makeup', name:'Featherweight Mascara', price:340, rating:4.4, reviews:112, img:'background_makeup.webp', desc:'Lengthens and separates without a trace of clumping or flaking by midday.', ingredients:'Beeswax, Panthenol, Carnauba Wax.', usage:'Wiggle from root to tip, apply a second coat only to the outer lashes.' },
  { id:'mk-07', category:'makeup', name:'Rose Gold Blush Duo', price:410, rating:4.6, reviews:64, badge:'New', img:'background_makeup.webp', desc:'A powder-and-cream duo that mimics the flush of a Cairo sunset across the cheeks.', ingredients:'Mica, Dimethicone, Squalane, Pigments.', usage:'Smile, apply cream shade to the apples, set with the powder shade for longevity.' },
  { id:'mk-08', category:'makeup', name:'Sheer Set Powder', price:360, rating:4.3, reviews:51, img:'background_makeup.webp', desc:'A translucent finishing powder that locks makeup in place without flattening it.', ingredients:'Silica, Rice Starch, Kaolin.', usage:'Press lightly with a puff over areas prone to shine.' },

  // ---- Skin Care ----
  { id:'sk-01', category:'skincare', name:'Radiance Vitamin C Serum', price:590, oldPrice:690, rating:4.9, reviews:412, badge:'Best Seller', img:'background_skincare.webp', desc:'A stabilized 15% vitamin C serum that brightens tone and softens fine lines over time.', ingredients:'Ascorbic Acid, Ferulic Acid, Vitamin E, Hyaluronic Acid.', usage:'Apply three drops each morning before moisturizer and SPF.' },
  { id:'sk-02', category:'skincare', name:'Overnight Repair Cream', price:720, rating:4.8, reviews:245, badge:'Best Seller', img:'background_skincare.webp', desc:'A rich, barrier-repairing night cream that lets skin wake up visibly rested.', ingredients:'Ceramides, Niacinamide, Shea Butter, Peptides.', usage:'Massage over cleansed skin as the final step of the evening routine.' },
  { id:'sk-03', category:'skincare', name:'Rose Quartz Hydrating Toner', price:280, rating:4.5, reviews:88, img:'background_skincare.webp', desc:'An alcohol-free toner that preps skin to drink in every product that follows.', ingredients:'Rose Water, Glycerin, Panthenol.', usage:'Sweep across the face with a cotton pad after cleansing.' },
  { id:'sk-04', category:'skincare', name:'Clay Detox Mask', price:340, rating:4.4, reviews:67, img:'background_skincare.webp', desc:'A mineral-rich mask that draws out impurities without stripping moisture.', ingredients:'Kaolin, Bentonite Clay, Aloe Vera.', usage:'Apply a thin layer twice weekly, rinse after ten minutes.' },
  { id:'sk-05', category:'skincare', name:'Gentle Renewal Exfoliant', price:395, rating:4.6, reviews:120, badge:'New', img:'background_skincare.webp', desc:'A leave-on AHA/BHA blend that resurfaces skin without the sting.', ingredients:'Glycolic Acid, Salicylic Acid, Centella Asiatica.', usage:'Apply on dry skin at night, two to three times a week.' },
  { id:'sk-06', category:'skincare', name:'Barrier Repair Moisturizer', price:460, rating:4.7, reviews:156, img:'background_skincare.webp', desc:'A cushiony cream that restores comfort to reactive, over-exfoliated skin.', ingredients:'Ceramide NP, Cholesterol, Fatty Acids.', usage:'Apply morning and night as the last step of skincare.' },
  { id:'sk-07', category:'skincare', name:'Eye Contour Elixir', price:410, rating:4.5, reviews:73, img:'background_skincare.webp', desc:'A cooling roll-on that visibly reduces puffiness and fine lines around the eyes.', ingredients:'Caffeine, Peptides, Hyaluronic Acid.', usage:'Roll gently around the orbital bone morning and night.' },
  { id:'sk-08', category:'skincare', name:'SPF 50 Silk Shield', price:330, rating:4.8, reviews:198, badge:'Best Seller', img:'background_skincare.webp', desc:'A weightless, no-white-cast sunscreen that layers invisibly under makeup.', ingredients:'Zinc Oxide, Niacinamide, Vitamin E.', usage:'Apply generously as the last step every morning, reapply midday.' },

  // ---- Hair Care ----
  { id:'hc-01', category:'haircare', name:'Argan Repair Elixir Oil', price:480, oldPrice:560, rating:4.8, reviews:189, badge:'Best Seller', img:'background_haircare.webp', desc:'A finishing oil that seals split ends and adds glass-like shine without weight.', ingredients:'Argan Oil, Vitamin E, Camellia Seed Oil.', usage:'Warm two drops between palms and smooth over mid-lengths and ends.' },
  { id:'hc-02', category:'haircare', name:'Silk Bond Shampoo', price:290, rating:4.5, reviews:104, img:'background_haircare.webp', desc:'A sulfate-free shampoo that cleanses gently while reinforcing the hair\u2019s internal bonds.', ingredients:'Amino Acids, Biotin, Coconut-Derived Surfactants.', usage:'Massage into wet hair, lather, rinse thoroughly.' },
  { id:'hc-03', category:'haircare', name:'Deep Nourish Hair Mask', price:410, rating:4.7, reviews:132, badge:'New', img:'background_haircare.webp', desc:'A once-weekly intensive treatment that rebuilds moisture from root to tip.', ingredients:'Shea Butter, Keratin, Panthenol.', usage:'Apply to damp hair, leave for ten minutes, rinse.' },
  { id:'hc-04', category:'haircare', name:'Volume Root Mist', price:260, rating:4.3, reviews:58, img:'background_haircare.webp', desc:'A weightless root spray that lifts flat hair without any stiffness.', ingredients:'Rice Protein, Panthenol, Polymer Blend.', usage:'Spray at the roots on damp hair before blow-drying.' },
  { id:'hc-05', category:'haircare', name:'Heat Shield Leave-In Spray', price:300, rating:4.6, reviews:97, img:'background_haircare.webp', desc:'Protects up to 230\u00b0C while detangling and smoothing in one step.', ingredients:'Cyclopentasiloxane, Keratin, UV Filters.', usage:'Mist evenly through damp hair before heat styling.' },
  { id:'hc-06', category:'haircare', name:'Scalp Renewal Serum', price:440, rating:4.6, reviews:81, img:'background_haircare.webp', desc:'A lightweight tonic that soothes the scalp and supports visibly fuller hair.', ingredients:'Caffeine, Niacinamide, Peppermint Oil.', usage:'Apply directly to scalp nightly, massage for one minute.' },

  // ---- Body Care ----
  { id:'bd-01', category:'bodycare', name:'Whipped Shea Body Butter', price:350, oldPrice:420, rating:4.8, reviews:176, badge:'Best Seller', img:'background_bodycare.webp', desc:'A cloud-textured butter that melts into skin for twenty-four-hour softness.', ingredients:'Shea Butter, Cocoa Butter, Sweet Almond Oil.', usage:'Massage generously over damp skin after showering.' },
  { id:'bd-02', category:'bodycare', name:'Silk Polish Sugar Scrub', price:310, rating:4.6, reviews:92, img:'background_bodycare.webp', desc:'Fine sugar crystals buff away roughness while oils replenish softness.', ingredients:'Sugar, Coconut Oil, Vitamin E.', usage:'Massage in circular motions on damp skin, rinse well.' },
  { id:'bd-03', category:'bodycare', name:'Rose Gold Body Oil', price:400, rating:4.7, reviews:110, badge:'New', img:'background_bodycare.webp', desc:'A dry-touch oil with a fine shimmer that leaves skin luminous, never greasy.', ingredients:'Jojoba Oil, Mica, Vitamin E.', usage:'Smooth over damp or dry skin, focusing on collarbones and legs.' },
  { id:'bd-04', category:'bodycare', name:'Silken Hand Cream', price:180, rating:4.4, reviews:64, img:'background_bodycare.webp', desc:'A fast-absorbing cream that softens hands without any residue.', ingredients:'Glycerin, Shea Butter, Panthenol.', usage:'Apply as needed throughout the day.' },
  { id:'bd-05', category:'bodycare', name:'Firming Body Serum', price:460, rating:4.5, reviews:70, img:'background_bodycare.webp', desc:'A concentrated serum that visibly improves skin elasticity with regular use.', ingredients:'Peptides, Caffeine, Centella Asiatica.', usage:'Massage upward over targeted areas twice daily.' },
  { id:'bd-06', category:'bodycare', name:'Velvet Bath Soak', price:260, rating:4.6, reviews:55, img:'background_bodycare.webp', desc:'Mineral salts and rose petals turn an ordinary bath into a ritual.', ingredients:'Epsom Salt, Dead Sea Salt, Rose Petals.', usage:'Dissolve two cups under warm running water.' },

  // ---- Perfumes ----
  { id:'pf-01', category:'perfumes', name:'Aura Noir Eau de Parfum', price:1250, oldPrice:1450, rating:4.9, reviews:320, badge:'Best Seller', img:'background_perfume.webp', desc:'A smoky amber and oud composition for evenings that need no introduction.', ingredients:'Oud, Amber, Dark Vanilla, Cedarwood.', usage:'Apply to pulse points; layer with the matching body oil for depth.' },
  { id:'pf-02', category:'perfumes', name:'Rose Mirage Eau de Parfum', price:1100, rating:4.7, reviews:198, img:'background_perfume.webp', desc:'A luminous rose wrapped in soft musk and a whisper of pink pepper.', ingredients:'Bulgarian Rose, White Musk, Pink Pepper.', usage:'Spray at the wrists, neck, and behind the ears.' },
  { id:'pf-03', category:'perfumes', name:'Golden Vanilla Elixir', price:1180, rating:4.8, reviews:167, badge:'New', img:'background_perfume.webp', desc:'A gourmand vanilla softened with sandalwood for a warm, skin-like finish.', ingredients:'Madagascar Vanilla, Sandalwood, Tonka Bean.', usage:'One or two sprays are enough to last well into the evening.' },
  { id:'pf-04', category:'perfumes', name:'Velvet Oud Travel Set', price:690, rating:4.5, reviews:84, img:'background_perfume.webp', desc:'Three 15ml discovery bottles of the house\u2019s most-loved oud blends.', ingredients:'Oud, Rose, Amber, Musk (varies by bottle).', usage:'Ideal for travel; store away from direct sunlight.' },
];

const CATEGORY_META = {
  makeup:   { label:'Makeup',    bg:'background_makeup.webp',   icon:'icon_makeup.webp',    tagline:'Color that plays by your rules', desc:'From featherlight bases to statement lips, discover makeup built for long wear and effortless blending.' },
  skincare: { label:'Skin Care', bg:'background_skincare.webp', icon:'icon_skincare.webp',  tagline:'Radiance, one ritual at a time', desc:'Serums, creams, and treatments formulated to bring out your skin\u2019s natural glow.' },
  haircare: { label:'Hair Care', bg:'background_haircare.webp', icon:'icon_hair_Care.webp', tagline:'Strength you can see and feel',   desc:'Nourishing oils, masks, and treatments for hair that moves with confidence.' },
  bodycare: { label:'Body Care', bg:'background_bodycare.webp', icon:'icon_bodycare.webp',  tagline:'Softness from head to toe',      desc:'Butters, scrubs, and oils that turn everyday care into a small luxury.' },
  perfumes: { label:'Perfumes',  bg:'background_perfume.webp',  icon:'icon_perfume.webp',   tagline:'A signature you can wear',       desc:'Layered, long-lasting fragrances crafted to become part of your story.' },
};

function lyProduct(id){ return PRODUCTS.find(p=>p.id===id); }
function lyByCategory(cat){ return PRODUCTS.filter(p=>p.category===cat); }
